# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'hardpointWindowzlJtMd.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sys

class Ui_HardPointEditWindow(object):
    def setupUi(self, HardPointEditWindow):
        if not HardPointEditWindow.objectName():
            HardPointEditWindow.setObjectName(u"HardPointEditWindow")
        HardPointEditWindow.resize(519, 507)
        self.comboBox = QComboBox(HardPointEditWindow)
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(10, 40, 171, 22))
        self.label = QLabel(HardPointEditWindow)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 0, 171, 31))
        font = QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.checkBox = QCheckBox(HardPointEditWindow)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(10, 70, 181, 31))
        self.checkBox_2 = QCheckBox(HardPointEditWindow)
        self.checkBox_2.setObjectName(u"checkBox_2")
        self.checkBox_2.setGeometry(QRect(10, 100, 181, 31))
        self.spinBox = QSpinBox(HardPointEditWindow)
        self.spinBox.setObjectName(u"spinBox")
        self.spinBox.setGeometry(QRect(80, 140, 61, 31))
        self.spinBox.setMaximum(1000)
        self.label_2 = QLabel(HardPointEditWindow)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 140, 61, 31))
        font1 = QFont()
        font1.setPointSize(14)
        self.label_2.setFont(font1)
        self.spinBox_2 = QSpinBox(HardPointEditWindow)
        self.spinBox_2.setObjectName(u"spinBox_2")
        self.spinBox_2.setGeometry(QRect(150, 190, 61, 31))
        self.spinBox_2.setMaximum(1000)
        self.label_3 = QLabel(HardPointEditWindow)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 190, 151, 31))
        self.label_3.setFont(font1)
        self.spinBox_3 = QSpinBox(HardPointEditWindow)
        self.spinBox_3.setObjectName(u"spinBox_3")
        self.spinBox_3.setGeometry(QRect(160, 230, 61, 31))
        self.spinBox_3.setMaximum(1000)
        self.label_4 = QLabel(HardPointEditWindow)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(10, 230, 151, 31))
        self.label_4.setFont(font1)
        self.comboBox_2 = QComboBox(HardPointEditWindow)
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(330, 20, 181, 21))
        self.label_5 = QLabel(HardPointEditWindow)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(250, 20, 121, 21))
        self.comboBox_3 = QComboBox(HardPointEditWindow)
        self.comboBox_3.addItem("")
        self.comboBox_3.setObjectName(u"comboBox_3")
        self.comboBox_3.setGeometry(QRect(330, 60, 181, 21))
        self.label_6 = QLabel(HardPointEditWindow)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(250, 60, 121, 21))
        self.doubleSpinBox = QDoubleSpinBox(HardPointEditWindow)
        self.doubleSpinBox.setObjectName(u"doubleSpinBox")
        self.doubleSpinBox.setGeometry(QRect(450, 100, 62, 22))
        self.doubleSpinBox.setMaximum(1000)
        self.label_7 = QLabel(HardPointEditWindow)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(310, 90, 141, 41))
        self.doubleSpinBox_2 = QDoubleSpinBox(HardPointEditWindow)
        self.doubleSpinBox_2.setObjectName(u"doubleSpinBox_2")
        self.doubleSpinBox_2.setGeometry(QRect(450, 140, 62, 22))
        self.doubleSpinBox_2.setMaximum(1000)
        self.label_8 = QLabel(HardPointEditWindow)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(310, 130, 141, 41))
        self.spinBox_4 = QSpinBox(HardPointEditWindow)
        self.spinBox_4.setObjectName(u"spinBox_4")
        self.spinBox_4.setGeometry(QRect(470, 180, 42, 22))
        self.spinBox_4.setMaximum(1000)
        self.label_9 = QLabel(HardPointEditWindow)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(400, 180, 61, 21))
        self.doubleSpinBox_3 = QDoubleSpinBox(HardPointEditWindow)
        self.doubleSpinBox_3.setObjectName(u"doubleSpinBox_3")
        self.doubleSpinBox_3.setGeometry(QRect(450, 210, 62, 22))
        self.doubleSpinBox_3.setMaximum(1000)
        self.label_10 = QLabel(HardPointEditWindow)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(310, 200, 131, 41))
        self.spinBox_5 = QSpinBox(HardPointEditWindow)
        self.spinBox_5.setObjectName(u"spinBox_5")
        self.spinBox_5.setGeometry(QRect(441, 240, 71, 31))
        self.spinBox_5.setMaximum(100000)
        self.label_11 = QLabel(HardPointEditWindow)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(340, 240, 101, 31))
        self.tableWidget = QTableWidget(HardPointEditWindow)
        if (self.tableWidget.columnCount() < 1):
            self.tableWidget.setColumnCount(1)
        __qtablewidgetitem = QTableWidgetItem()
        __qtablewidgetitem.setTextAlignment(Qt.AlignCenter);
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        if (self.tableWidget.rowCount() < 8):
            self.tableWidget.setRowCount(8)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, __qtablewidgetitem8)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setGeometry(QRect(195, 280, 301, 211))
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        self.tableWidget.verticalHeader().setMinimumSectionSize(3)

        self.retranslateUi(HardPointEditWindow)

        QMetaObject.connectSlotsByName(HardPointEditWindow)
    # setupUi

    def retranslateUi(self, HardPointEditWindow):
        HardPointEditWindow.setWindowTitle(QCoreApplication.translate("HardPointEditWindow", u"HardPoints_Hammerhead - HP_Hammerhead_01", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("HardPointEditWindow", u"Laser", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("HardPointEditWindow", u"Shield", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("HardPointEditWindow", u"Engine", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("HardPointEditWindow", u"Special", None))
        self.comboBox.setItemText(4, QCoreApplication.translate("HardPointEditWindow", u"Mass Driver", None))
        self.comboBox.setItemText(5, QCoreApplication.translate("HardPointEditWindow", u"Ion", None))

        self.label.setText(QCoreApplication.translate("HardPointEditWindow", u"HardPoint Type", None))
        self.checkBox.setText(QCoreApplication.translate("HardPointEditWindow", u"Is Targetable", None))
        self.checkBox_2.setText(QCoreApplication.translate("HardPointEditWindow", u"Is Destroyable", None))
        self.label_2.setText(QCoreApplication.translate("HardPointEditWindow", u"Health", None))
        self.label_3.setText(QCoreApplication.translate("HardPointEditWindow", u"Fire Cone Width", None))
        self.label_4.setText(QCoreApplication.translate("HardPointEditWindow", u"Fire Cone Height", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("HardPointEditWindow", u"Damage_Calamari_Cruiser", None))

        self.label_5.setText(QCoreApplication.translate("HardPointEditWindow", u"Damage Type", None))
        self.comboBox_3.setItemText(0, QCoreApplication.translate("HardPointEditWindow", u"Proj_Ship_Turbolaser_Red", None))

        self.label_6.setText(QCoreApplication.translate("HardPointEditWindow", u"Projectile Type", None))
        self.label_7.setText(QCoreApplication.translate("HardPointEditWindow", u"Fire Min Recharge (seconds)", None))
        self.label_8.setText(QCoreApplication.translate("HardPointEditWindow", u"Fire Min Recharge (seconds)", None))
        self.label_9.setText(QCoreApplication.translate("HardPointEditWindow", u"Pulse Count", None))
        self.label_10.setText(QCoreApplication.translate("HardPointEditWindow", u"Fire Pulse Delay (seconds)", None))
        self.label_11.setText(QCoreApplication.translate("HardPointEditWindow", u"Fire Range Distance", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("HardPointEditWindow", u"Inaccuracy Distance", None));
        ___qtablewidgetitem1 = self.tableWidget.verticalHeaderItem(0)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("HardPointEditWindow", u"Fighter", None));
        ___qtablewidgetitem2 = self.tableWidget.verticalHeaderItem(1)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("HardPointEditWindow", u"Bomber", None));
        ___qtablewidgetitem3 = self.tableWidget.verticalHeaderItem(2)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("HardPointEditWindow", u"Transport", None));
        ___qtablewidgetitem4 = self.tableWidget.verticalHeaderItem(3)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("HardPointEditWindow", u"Corvette", None));
        ___qtablewidgetitem5 = self.tableWidget.verticalHeaderItem(4)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("HardPointEditWindow", u"Frigate", None));
        ___qtablewidgetitem6 = self.tableWidget.verticalHeaderItem(5)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("HardPointEditWindow", u"Capital", None));
        ___qtablewidgetitem7 = self.tableWidget.verticalHeaderItem(6)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("HardPointEditWindow", u"SuperCapital", None));
    # retranslateUi

app = QApplication(sys.argv)
TestQFileDialog = QWidget()
ui = Ui_HardPointEditWindow()
ui.setupUi(TestQFileDialog)
TestQFileDialog.show()
sys.exit(app.exec_())